- name: pihole - stat /etc/pihole/setupVars.conf
  stat:
    path: /etc/pihole/setupVars.conf
  register: etc_pihole
- name: pihole - mkdir /etc/pihole
  file:
    state: directory
    path: /etc/pihole
    owner: root
    group: root
    mode: 0755
  when: not(etc_pihole.stat.exists | default(false)) # Avoid changing perms from what pihole sets
- name: pihole - /etc/pihole/setupVars.conf
  template:
    src: pihole-setupvars.conf.j2
    dest: /etc/pihole/setupVars.conf
    owner: root
    group: root
    mode: 0644
  when: not(etc_pihole.stat.exists | default(false)) # Avoid changing values that have been reconfigured already
