- name: pihole - /etc/dnsmasq.d/02-local.conf
  template:
    src: pihole-02-local.conf.j2
    dest: /etc/dnsmasq.d/02-local.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - pihole restartdns
- name: pihole - /etc/pihole/custom.list
  template:
    src: pihole-custom.list.j2
    dest: /etc/pihole/custom.list
    owner: root
    group: root
    mode: 0644
  notify:
  - pihole restartdns reload